version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    command: bash -c "go get github.com/codegangsta/gin && gin -i"
    volumes:
      - .:/go/src/github.com/onestay/MarathonTools-API
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
volumes:
  mongo-data:
  redis-data: