version: '3'

services:
  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis    
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
volumes:
  mongo-data:
  redis-data:
